### ISSUE TITLE
Link to demonstration server broken

### ISSUE THREAD

**Issue by lbeltrame** [chapmanb/o8#2]
As the title says, the demonstration server linked in the README leads to a nginx error.

**Comment by liefeld** [comment]
Luca

I am a GenomeSpace developer but I am not familiar with Brad's O8 project
so I think we'll need him or another of the developers of it to help with
this

Ted

On Tue, Jan 21, 2014 at 6:25 AM, Luca Beltrame notifications@github.comwrote:

> As the title says, the demonstration server linked in the README leads to
> a nginx error.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/chapmanb/o8/issues/2
> .

## 

Ted Liefeld                                      Voice:      (617) 714-7490
Cancer Genomics Informatics           Front desk: (617) 714-7000
Broad Institute                                 Fax:        (617) 714-8955
7 Cambridge Center                          Email:
liefeld@broadinstitute.org
Cambridge, MA 02142                       http://www.broad.mit.edu/cancer

**Comment by chapmanb** [comment]
Luca;
Apologies, the server went down but I brought it back up again so the demo server is running again. Thanks for the heads up.
