### ISSUE TITLE
Demo server down

### ISSUE THREAD

**Issue by timknut** [chapmanb/o8#3]
Would be great if the demo server was up and running at http://variantviz.rc.fas.harvard.edu/

Regards, 
Tim

**Comment by chapmanb** [comment]
Tim;
Apologies for the downtime. FAS Research computing kindly host this on a virtual machine, and there was a downtime this week due to issues with a storage array. Everything is now stabilized and the demo server is back online. Thanks for the interest and sorry again about the problem.
